-- generated by github.com/mackee/go-genddl. DO NOT EDIT!!!

DROP TABLE IF EXISTS "chat_message";

CREATE TABLE "chat_message" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "message" TEXT NOT NULL,
    "created_at" INTEGER NOT NULL
) ;
CREATE INDEX chat_message_created_at ON chat_message ("created_at");

